### ISSUE TITLE
"FAQ" part to README

### ISSUE THREAD

**Issue by kahilah** [Aalto-CFD/DLBFoam#4] opened 2021-06-09 06:59 UTC
There should be a FAQ part in the README.

For example, from experience I know that when using pyjac, it is very easy to get an error:  
```symbol lookup error: 
/path/to/user/OpenFoam/linux64GccDPInt32Opt/lib/libchemistryModel_DLB.so:
 undefined symbol: eval_h
```

README should state that in this occasion you pyjac library linkin is not established. Fix it like ....

**Comment by blttkgl** [comment] 2021-06-17 00:28
Hey folks, please comment here the most common error/warning messages you encounter when you forget to set something properly. @drhcelik perhaps you can get the ball rolling? For instance one common issue is the tutorial hanging in parallel because the user have both openblas and lapacke installed.

Can we assign this (and other tickets) to individuals and set deadlines if possible? We should be clearing tickets as they come to avoid becoming legacy code in a year or so.

Bulut

**Comment by drhcelik** [comment] 2021-06-17 07:19
Well, in addition to your comments, I can add this warning:
`could not open file mkl_lapack.h for source file ODESolvers/seulex_LAPACK/seulex_LAPACK.C due to No such file or directory
`

**Comment by moreff** [comment] 2021-06-17 09:03
Hi, thank you for your comments. 
I'll reproduce these warnings on my machine and add these to the readme.
We will handle this issue along with others as soon as possible

**Comment by blttkgl** [comment] 2021-06-26 23:48
@drhcelik  that is not exactly a warning. There is a if else statement in the ODE class looking to see if you want to compile MKL or non-MKL. If you compile non-MKL, everything is fine but it still tries to find the mkl_lapack.h file within the if statement. I'm pretty sure there is a more elegant way to solve this. Maybe @kahilah  can suggest something.

**Comment by drhcelik** [comment] 2021-06-27 04:46
Exactly @blttkgl, but maybe it can be ignored by a DLBFoam beginner level user safely till we find a better solution. 

I was trying to get rid of that warning when I compiled DLBFoam for the first time as I didn't know this and I realized that if statement a bit later.

**Comment by kahilah** [comment] 2021-06-27 17:21
It boils down to OpenFoam's wmake system (not the best one around) which produces this "feature".

**Comment by moreff** [comment] 2021-07-09 15:51
FAQ section is now added to readme

**Closed as completed by moreff** 2021-07-09 15:51 UTC
